- hosts: localhost
  connection: local
  remote_user: fmollura
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: Modify hostfile
    replace:
      path: /etc/hosts
      regexp: '.*ssltest-sorint.ml.*'
      replace: "{{ lookup('env','REMOTEIP') }}        ssltest-sorint.ml       www.ssltest-sorint.ml"
      backup: yes
